import type { PrismaClient } from "@prisma/client";

/**
 * Let `next build` finish without a database.
 *
 * Public pages are statically rendered, so the production build executes their
 * queries. In CI and inside `docker build` there is no database, and failing the
 * image build because one is missing at *compile* time is the wrong trade — the
 * pages must be generated against the production database anyway, which only
 * exists at runtime.
 *
 * So during the build phase only, a connection failure yields an empty result
 * instead of throwing. The page prerenders empty and ISR regenerates it with
 * real data on first request. Supplying a reachable DATABASE_URL at build time
 * still prerenders real content — this is the fallback, not the default.
 *
 * Deliberately narrow, because silently swallowing database errors is otherwise
 * a terrible idea:
 *   · build phase only (NEXT_PHASE), never at runtime;
 *   · connection/initialisation failures only — a malformed query still throws;
 *   · read operations only, so a failed write can never look like a success.
 */

const READ_OPS = new Set([
  "findMany",
  "findFirst",
  "findFirstOrThrow",
  "findUnique",
  "findUniqueOrThrow",
  "count",
  "aggregate",
  "groupBy",
]);

/** Prisma's "can't reach the database" family, by name and by message. */
function isConnectionError(err: unknown): boolean {
  if (!err || typeof err !== "object") return false;
  const name = (err as { name?: string }).name ?? "";
  const message = (err as { message?: string }).message ?? "";
  if (name === "PrismaClientInitializationError") return true;
  return (
    /Can't reach database server/i.test(message) ||
    /Environment variable not found: DATABASE_URL/i.test(message) ||
    /ECONNREFUSED|ENOTFOUND|EAI_AGAIN/i.test(message)
  );
}

function emptyFor(operation: string): unknown {
  switch (operation) {
    case "findMany":
    case "groupBy":
      return [];
    case "count":
      return 0;
    case "aggregate":
      return {};
    default:
      // findFirst / findUnique and their OrThrow variants: absent is null, and
      // callers already handle "not found" (usually with notFound()).
      return null;
  }
}

export function isBuildPhase(): boolean {
  return process.env.NEXT_PHASE === "phase-production-build";
}

/**
 * Wrap a client so build-time reads survive a missing database. Returns the
 * client untouched outside the build phase, so runtime behaviour is unchanged.
 */
export function withBuildGuard(client: PrismaClient): PrismaClient {
  if (!isBuildPhase()) return client;

  let warned = false;
  return client.$extends({
    name: "build-guard",
    query: {
      $allModels: {
        async $allOperations({ operation, args, query, model }) {
          try {
            return await query(args);
          } catch (err) {
            if (!READ_OPS.has(operation) || !isConnectionError(err)) throw err;
            if (!warned) {
              warned = true;
              console.warn(
                "[build-guard] no database during `next build` — DB-backed pages " +
                  "will prerender empty and be regenerated by ISR on first request. " +
                  "Pass a reachable DATABASE_URL to prerender real content.",
              );
            }
            console.warn(`[build-guard] ${model ?? "?"}.${operation} → empty`);
            return emptyFor(operation);
          }
        },
      },
    },
  }) as unknown as PrismaClient;
}
