FROM node:22-alpine

WORKDIR /app
COPY . .

RUN npm install -g pnpm
RUN pnpm install --no-frozen-lockfile

RUN pnpm --filter @vaidyasala/db generate
RUN pnpm --filter @vaidyasala/web build

ENV NODE_ENV production
EXPOSE 3000

CMD ["pnpm", "--filter", "@vaidyasala/web", "start"]
